travel/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create]

  get 'hotel_search', to: 'hotel_search#index'
  get 'hotel_search/results', to: 'hotel_search#results'
  get 'hotel_reviews', to: 'hotel_reviews#index'

  resources :hotels, only: [:index]

  get 'onsen_search', to: 'onsen_search#index'
  get 'onsen_search/results', to: 'onsen_search#results'
end

travel/app/models/hotel.rb
class Hotel < ApplicationRecord
end

travel/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
end

travel/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

travel/app/controllers/hotel_reviews_controller.rb
class HotelReviewsController < ApplicationController

  # ホテル情報の表示
  # and レビュー一覧の表示
  # and レビュー登録
  def index
    
    url = 'http://jws.jalan.net/APILite/HotelSearch/V1/'

    search_params = {
      key: ENV['JARAN_APPLICATION_ID'], # APIキー
      h_id: params[:code],
      count: 100,
    }

    conn = Faraday.new(url: url)
    response = conn.get '', search_params
    response_hash = Hash.from_xml(response.body)['Results']['Hotel']

    if !Hotel.where(code: response_hash['HotelID']).exists?
      @hotel = Hotel.new(
        code: response_hash['HotelID'],
        name: response_hash['HotelName'],
        postcode: response_hash['PostCode'],
        address: response_hash['HotelAddress'],
        ).save
    else
      @hotel = Hotel.where(code: response_hash['HotelID'])
    end

  end

end

travel/app/controllers/hotel_search_controller.rb
class HotelSearchController < ApplicationController

  def index
  end

  def results
    url = 'http://jws.jalan.net/APILite/HotelSearch/V1/'

    # 検索条件はフォームから取得して、動的に変えられるようにしましょう
    search_params = {
      key: ENV['JARAN_APPLICATION_ID'], # APIキー
      pref: params[:prefectures],
      count: 100,
    }

    conn = Faraday.new(url: url)
    response = conn.get '', search_params
    @hotels = Hash.from_xml(response.body)['Results']['Hotel']
  end

end

travel/app/controllers/onsen_search_controller.rb
class OnsenSearchController < ApplicationController


  def index
  end

  def results
    url = 'http://jws.jalan.net/APICommon/OnsenSearch/V1/'

    # 検索条件はフォームから取得して、動的に変えられるようにしましょう
    search_params = {
      key: ENV['JARAN_APPLICATION_ID'], # APIキー
      pref: params[:prefectures],
      count: 100,
      xml_ptn: 1,
    }

    conn = Faraday.new(url: url)
    response = conn.get '', search_params
    @onsens = Hash.from_xml(response.body)['Results']['Onsen']
  end
end

travel/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

travel/app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

travel/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  def show
  @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

travel/app/helpers/onsen_search_helper.rb
module OnsenSearchHelper
end

travel/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

travel/app/helpers/toppages_helper.rb
module ToppagesHelper
end

travel/app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

travel/app/views/hotel_reviews/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>ホテルの口コミサイト</title>
</head>
<body>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h2>モテるようになる薬</h2>
			<p>この薬を飲むと、美女からモテます。すごい薬です。モテるだけじゃなく健康にもなります。すごいです。すごいです。すごいです。すごいです。すごいです。すごいです。すごいです。</p>
			<hr>
		</div>
		<div class="col-xs-12">
			<h4>名前：山田 太郎さん（2016/9/1）</h4>
			<p>信じられません。モテすぎて困っています。すぐに買うべきです。おすすめです。おすすめです。おすすめです。おすすめです。おすすめです。</p>
		</div>
		<div class="col-xs-12">
			<h4>名前：佐々木 太郎さん（2016/7/28）</h4>
			<p>まったく効果ありません。買わないほうがいいです。買わないほうがいいです。買わないほうがいいです。買わないほうがいいです。買わないほうがいいです。</p>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		 <div class="col-xs-12">
		 	<h3>口コミを投稿する</h3>
			<form action="" method="post">
				<textarea name="add_review" class="form-control" placeholder="口コミを記入してください。"></textarea>
				<button type="submit" class="btn btn-default">投稿する</button>
			</form>
		 </div>
	</div>
</div>

travel/app/views/hotel_search/index.html.erb
<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(hotel_search_results_path, method: :get, class: 'form-inline') do %>
        <%= select_tag 'prefectures', options_for_select([
          ['北海道' , '010000'],
          ['青森県' , '020000'],
          ['岩手県' , '030000'],
          ['宮城県' , '040000'],
          ['秋田県' , '050000'],
          ['山形県' , '060000'],
          ['山形県' , '060000'],
          ['福島県' , '070000'],
          ['栃木県' , '080000'],
          ['群馬県' , '090000'],
          ['茨城県' , '100000'],
          ['埼玉県' , '110000'],
          ['千葉県' , '120000'],
          ['東京都', '130000'],
          ['神奈川県', '140000'],
          ['山梨県', '150000'],
          ['長野県', '160000'],
          ['新潟県', '170000'],
          ['富山県', '180000'],
          ['石川県', '190000'],
          ['福井県', '200000'],
          ['静岡県', '210000'],
          ['岐阜県', '220000'],
          ['愛知県', '230000'],
          ['三重県', '240000'],
          ['滋賀県', '250000'],
          ['京都府', '260000'],
          ['大阪府', '270000'],
          ['兵庫県', '280000'],
          ['奈良県', '290000'],
          ['和歌山県', '300000'],
          ['鳥取県', '310000'],
          ['島根県', '320000'],
          ['岡山県', '330000'],
          ['広島県', '340000'],
          ['山口県', '350000'],
          ['徳島県', '360000'],
          ['香川県', '370000'],
          ['愛媛県', '380000'],
          ['高知県', '390000'],
          ['福岡県', '400000'],
          ['佐賀県', '410000'],
          ['長崎県', '420000'],
          ['熊本県', '430000'],
          ['大分県', '440000'],
          ['宮崎県', '450000'],
          ['鹿児島県', '460000'],
          ['沖縄県', '470000']
        ]) %>
        <%= submit_tag '検索!!!', class: 'btn btn-success btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

travel/app/views/hotel_search/results.html.erb
<h1>ホテル検索結果</h1>

<% @hotels.each do |hotel| %>
  <%= link_to hotel['HotelName'], hotel_reviews_path(code: hotel['HotelID']) %>
  <img src="<%= hotel['PictureURL'] %>">
  <%= link_to '詳細はコチラ（外部リンク）', hotel['HotelDetailURL'] %>	
  <br>
<% end %>

travel/app/views/onsen_search/index.html.erb
<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(onsen_search_results_path, method: :get, class: 'form-inline') do %>
        <%= select_tag 'prefectures', options_for_select([
          ['北海道' , '010000'],
          ['青森県' , '020000'],
          ['岩手県' , '030000'],
          ['宮城県' , '040000'],
          ['秋田県' , '050000'],
          ['山形県' , '060000'],
          ['山形県' , '060000'],
          ['福島県' , '070000'],
          ['栃木県' , '080000'],
          ['群馬県' , '090000'],
          ['茨城県' , '100000'],
          ['埼玉県' , '110000'],
          ['千葉県' , '120000'],
          ['東京都', '130000'],
          ['神奈川県', '140000'],
          ['山梨県', '150000'],
          ['長野県', '160000'],
          ['新潟県', '170000'],
          ['富山県', '180000'],
          ['石川県', '190000'],
          ['福井県', '200000'],
          ['静岡県', '210000'],
          ['岐阜県', '220000'],
          ['愛知県', '230000'],
          ['三重県', '240000'],
          ['滋賀県', '250000'],
          ['京都府', '260000'],
          ['大阪府', '270000'],
          ['兵庫県', '280000'],
          ['奈良県', '290000'],
          ['和歌山県', '300000'],
          ['鳥取県', '310000'],
          ['島根県', '320000'],
          ['岡山県', '330000'],
          ['広島県', '340000'],
          ['山口県', '350000'],
          ['徳島県', '360000'],
          ['香川県', '370000'],
          ['愛媛県', '380000'],
          ['高知県', '390000'],
          ['福岡県', '400000'],
          ['佐賀県', '410000'],
          ['長崎県', '420000'],
          ['熊本県', '430000'],
          ['大分県', '440000'],
          ['宮崎県', '450000'],
          ['鹿児島県', '460000'],
          ['沖縄県', '470000']
        ]) %>
        <%= submit_tag '検索!!!', class: 'btn btn-success btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

travel/app/views/onsen_search/results.html.erb
<h1>温泉検索結果</h1>

<% @onsens.each do |onsen| %>
  <%= onsen['OnsenName'],hotel_reviews_path %>
  <%= link_to'詳細はコチラ', onsen['OnsenAreaURL'] %>	
  <br>
<% end %>

travel/app/views/toppages/index.html.erb
<% content_for :cover do %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <h1>最安値と最新の口コミをチェック</h1>
          <% unless logged_in? %>
            <%= link_to '最安値と最新の口コミをチェックする', signup_path, class: 'btn btn-success btn-lg' %>
          <% end %>      
      </div>
    </div>
  </div>
<% end %>

<p>テスト</p>

travel/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

travel/app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

travel/app/views/users/show.html.erb
<div class="user-profile">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
</div>